spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    test-while-idle: true
    validation-query: SELECT 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
example:
  property: I AM A DEFAULT
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: {cipher} e6f0b3d1001768c4d2dd002b6f9d6466114d274304ed31b223a1e82a21095651
example:
  property: I AM A DEV!
